### PR TITLE
Removed swagger-ui since it's been killed

### PR DESCRIPTION
**Pull request by neovita**

### CODE REVIEW

**Comment by jByrneSpringer** [comment]
The link to swagger is still there.  Is that not what you intended to remove?

**Review by karolinasmitaite — APPROVED** [review]
Just click on "Merge pull request" ;)

**Comment by karolinasmitaite** [comment]
> The link to swagger is still there. Is that not what you intended to remove?

@jByrneSpringer it's _the other_ Swagger ;D

**Comment by sebastianschnock** [comment]
nice work!

**Review by sebastianschnock — APPROVED** [review]

**Comment by neovita** [comment]
This was such a swaggery document @jByrneSpringer and @sebastianschnock :)

**Pull request merged**
